version: "3.9"

services:
  backend:
    build:
      context: ./python-server
    container_name: hackcmu-backend
    ports:
      - "8000:8000"
    volumes:
      - hf_cache:/root/.cache/huggingface
    restart: unless-stopped

  frontend:
    build:
      context: ./client
    container_name: hackcmu-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  hf_cache:


